### ISSUE TITLE
Clarification about Skyrim SE

### ISSUE THREAD

**Issue by ReplicaObscura** [shadeMe/ConSkrybe#1]
Does this support Skyrim SE, or are there plans for that? I only see it on Oldrim's Nexus site, but I would really like to be able to utilize it in SE if it would work.

**Comment by shadeMe** [comment]
There are no plans to port this to Skyrim SE, sorry.

**Comment by ReplicaObscura** [comment]
Is there a technical reason it wouldn't work, or do you just not have a desire to put this out for SE? Would you allow someone else to port this to SE?
